name: Postman API Tests with Newman

on:
  push:
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman + reporters
        run: |
          npm install -g newman newman-reporter-htmlextra newman-reporter-junitfull

      - name: Run Smoke Tests
        env:
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
        run: |
          mkdir -p reports
          newman run postman/api_test_framework.collection.json \
            -e postman/api_test_framework.environment.json \
            --env-var "x-api-key=$CAT_API_KEY" \
            --folder "favourites" \
            -r cli,htmlextra,junitfull \
            --reporter-htmlextra-export reports/smoke-report.html \
            --reporter-junitfull-export reports/smoke-junit.xml

      - name: Run Negative Tests
        env:
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
        run: |
          newman run postman/api_test_framework.collection.json \
            -e postman/api_test_framework.environment.json \
            --env-var "x-api-key=$CAT_API_KEY" \
            --folder "negative testing" \
            -r cli,htmlextra,junitfull \
            --reporter-htmlextra-export reports/negative-report.html \
            --reporter-junitfull-export reports/negative-junit.xml

      - name: Upload HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-reports
          path: reports/*.html

      - name: Upload JUnit XML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-junit-reports
          path: reports/*.xml